# This is a basic workflow to help you get started with Actions

name: AthenaCI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: use Node.js 14.16.0
        # 使用action库  actions/setup-node安装node
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.0
      # Runs a single command using the runners shell
      - name: use yarn
        # 使用action库  actions/setup-node安装node
        run: npm install yarn -g
      # Runs a single command using the runners shell
      - name: Install Dependencies
        run: yarn
      # Runs a set of commands using the runners shell
      - name: Build
        run: yarn build
      - name: deploy file to server
        uses: easingthemes/ssh-deploy@v2.1.1
        with:  
          # 私钥
          SSH_PRIVATE_KEY: ${{ secrets.ALIYUN }}
          # scp参数
          # 源目录，编译后生成的文件目录
          SOURCE: "./dist"
          # 服务器ip：换成你的服务器IP
          REMOTE_HOST: '${{ secrets.ALIYUN_IP }}'
          # 用户
          REMOTE_USER: "root"
          # 目标地址 你在服务器上部署代码的地方
          TARGET: '/var/www/athena'